---
title: "Exploratory Data Analysis"
author: '2466057'
date: "2024-05-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 8, fig.width = 10)
```

```{r}
library(tidyverse)
library(here)
```

```{r}

data <- read_csv(here::here("data/TidyData.csv"))
metadata <- read_csv(here::here("data/MetaData.csv"))

```

```{r}

long_data <- data |> 
  pivot_longer(cols = !c(DiseaseSubtype, DiseaseSubtypeFull, PseudoID), names_to = "mRNA", values_to = "deltaCt")

```

```{r}
data |> 
  count(DiseaseSubtypeFull)
```


```{r}
data |> 
  ggplot(aes(x = DiseaseSubtype, fill = DiseaseSubtypeFull))+
  geom_histogram()
```

```{r}

 long_data |> 
  ggplot(aes(x = deltaCt, fill = DiseaseSubtypeFull))+
  geom_histogram(alpha = .8, position="identity", show.legend = F)+
  facet_grid(~DiseaseSubtypeFull)

```

```{r}

 long_data |> 
  ggplot(aes(x = DiseaseSubtypeFull, y = deltaCt, fill = DiseaseSubtypeFull))+
  geom_violin(alpha = .5, show.legend = F) + 
  geom_boxplot(alpha = .8, width = .3, show.legend = F)

```

```{r}
long_summary <- long_data |> 
  summarise(.by = c(mRNA, DiseaseSubtype, DiseaseSubtypeFull), 
            mean = mean(deltaCt),
            sd = sd(deltaCt))
```


```{r}
total_sample = c(50, 100, 200, 400, 800, 1600)
imbalance = seq(0.5, 0.95, .05)
exp_id = rep(rep(1:( length(total_sample) * length(imbalance)), times = 2), times = long_summary$mRNA |> n_distinct())

set.seed(1)

sim_dfs <- long_summary |> 
  filter(DiseaseSubtypeFull %in% c("PHT", "PA")) |> 
  # pivot_wider(id_cols = mRNA, names_from = DiseaseSubtypeFull, values_from = c(mean, sd)) |> 
  mutate(
    total_samples = list(total_sample),
    imbalance = list(imbalance)) |> 
  unnest(cols = total_samples) |>
  unnest(cols = imbalance) |> 
  mutate(exp_id = exp_id) |>
  mutate(
    sample_size = if_else(
      DiseaseSubtypeFull == "PHT", 
      ceiling(total_samples * imbalance), 
      floor(total_samples * (1 - imbalance))
      ), 
    row_id = 1:n()) |> 
  mutate(.by = row_id, 
    sim_values = list(rnorm(n = sample_size, mean = mean, sd = sd))
    ) |> 
  select(exp_id, mRNA, DiseaseSubtype, DiseaseSubtypeFull, total_samples, imbalance, sim_values) |> 
  unnest(sim_values) |> 
  pivot_wider(id_cols = c(exp_id, DiseaseSubtype, DiseaseSubtypeFull, total_samples, imbalance), 
              names_from = mRNA, 
              values_from = sim_values, 
              values_fn = list) |> 
  unnest(everything()) |> 
  mutate(imbalance = imbalance * 100) |> 
  group_split(exp_id)
```

```{r}

write_csv_files <- function(x) {
  
  .filename <- paste0("sim_", x$total_samples[[1]], "_", x$imbalance[[1]], ".csv")
  
  readr::write_csv(x = x, file = here::here(paste0("data/sim_data/", .filename)))
  
}

walk(.x = sim_dfs, 
     # .f = ~ readr::write_csv(x = .x, file = here::here("sim_data/"))
     .f = write_csv_files, 
     .progress = T
     )

```



```{r}
long_summary |> 
  ggplot(aes(x = mean, fill = DiseaseSubtypeFull, colour = DiseaseSubtypeFull))+
  geom_histogram(bins = 50, position = "identity", alpha = .3)
```

```{r}

long_summary |> 
  ggplot(aes(x = reorder(mRNA, mean), y = mean, colour = DiseaseSubtypeFull)) +
  geom_point()

```


```{r}
long_summary |> 
  ggplot(aes(x = sd, fill = DiseaseSubtypeFull, colour = DiseaseSubtypeFull))+
  geom_histogram(bins = 50, position = "identity", alpha = .3)


```

```{r}

pca <- data |> 
  select(-PseudoID, -starts_with("Disease")) |> 
  select(where(is.numeric)) |> 
  prcomp(scale = T, rank. = 10)
  
pca_fit <- pca |> 
  broom::augment(data)

pca_hull <- pca_fit |> 
  group_by(DiseaseSubtypeFull) |>  
  slice(chull(.fittedPC1, .fittedPC2))

summary(pca)
```

```{r}

plot_pca_grid <- function(df, hull_df, group, size = 2, labels = c(), values = c()){
  
  legend_title <- dplyr::enexpr(group)
  
  df |> 
    ggplot(
      aes(x = .fittedPC1, y = .fittedPC2, colour = {{group}}, fill = {{group}})
    )+
    geom_point(size = size)+
    geom_vline(xintercept = 0)+
    geom_hline(yintercept = 0)+
    # stat_ellipse(geom = "polygon", level = 0.95, alpha = 0.2, show.legend = F)+
    geom_polygon(data = hull_df,
                 colour = NA, 
                 alpha = 0.3,
                 show.legend = FALSE)+
    scale_color_manual(paste0(legend_title), 
                       labels = labels,
                       values = values, 
                       guide = guide_legend(override.aes = list(size = 5, shape = 15, alpha = 1)))+
    guides(fill = "none")
}

format_pca_axes <- function(graph, pca_obj){
  
  var <- broom::tidy(pca_obj, matrix = "eigenvalues") |> 
    pull(percent)
  
  var <- round(var * 100, 2)
  
  graph +
    scale_x_continuous(paste0("PC 1 (", var[[1]], "%)"))+
    scale_y_continuous(paste0("PC 2 (", var[[2]], "%)"))
  
}

```

```{r, fig.height=8, fig.width=10}

labels = c("HV", "PA", "CS", "PHT", "PPGL")
values = c("HV" = "#0f4c5c", "PA" = "#e36414", "CS" = "#fb8b24", "PHT" = "#9a031e", "PPGL" = "#5f0f40")
values = c("HV" = "#177e89", "PA" = "#084c61", "CS" = "#db3a34", "PHT" = "#ffc857", "PPGL" = "#323031")

.p1 <- pca_fit |>
  plot_pca_grid(
    hull_df = pca_hull,  
    group = DiseaseSubtypeFull, 
    labels = labels, 
    values = values)

format_pca_axes(.p1, pca)

```

```{r, fig.width=13, fig.height=13}
library(ggcorrplot)

num_data <- data |> 
  select(where(is.numeric)) |> 
  select(!DiseaseSubtype)

cor <- num_data |> 
  scale() |> 
  cor()

ggcorrplot(cor, colors = c("darkcyan", "white", "red"),
           # type = "lower", 
           hc.order = T,
           lab = F)
  
```

