---
title: "Hyperparameter Tuning"
author: '2466057'
date: "2024-05-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(here)

```

```{r}

raw_metrics <- read_csv(here("data/merged/metrics_merged.csv"))
raw_params <- read_csv(here("data/merged/params_merged.csv"))

```

```{r}

metrics <- raw_metrics |> 
  mutate(
    model_code = str_extract(id, "[A-Z]+"), 
    model_id = str_extract(id, "[A-Z]+-[0-9]+")) |> 
  relocate(any_of(c("model_code", "model_id")), .after = id)

metrics

```

```{r}

params <- raw_params |> 
  mutate(
    model_code = str_extract(model_id, "[A-Z]+")) |> 
  relocate(any_of(c("model_code", "model_id")))

params


```


```{r}
verify_code_in_tibble <- function(params, code){
  
  .all_codes <- params |> 
    pluck("model_code") |> 
    unique()
  
  if(!is.element(code, .all_codes)) {
    message = stringr::str_c(
      "Please ensure the `code` is in the tibble!\n - Received '", code,
      "' but expected an element in '", paste0(.all_codes, collapse = "', '"), "'"
      )
    
    stop(message)
  }else{
    
    return(TRUE)
    
  }
}

verify_is_tibble <- function(arg_value, arg_name){
  
  if (missing(arg_value) || !is.tibble(arg_value)){ 
    stop(paste0("Please ensure you supplied a tibble for `", arg_name, "`!"))
  }else{
    
    return(TRUE)
    
  }
}

verify_is_string <- function(arg_value, arg_name){
   
  if (missing(arg_value) || !is.character(arg_value)){ 
     stop(paste0("Please ensure you supplied a string for `", arg_name, "`!"))
  }else{
      
    return(TRUE)
    
  }
}

extract_hyperparams <- function(params, code){
  
  # verify_is_tibble(params, "params")
  # verify_is_string(code, "code")
  # verify_code_in_tibble(params, code)
    
  .hyperparams <- params |> 
    filter(model_code == code) |> 
    pluck("param") |> 
    unique()
   
  return(.hyperparams)

}

pivot_param_tibble <- function(params, code){
  
  # verify_is_tibble(params, "params")
  # verify_is_string(code, "code")
  # verify_code_in_tibble(code, params)
  
  .hyperparams <- extract_hyperparams(params, code)
  
  ## filter than pivot the params table
  .pivot_params <- params |> 
    filter(model_code == code) |> 
    pivot_wider(
      id_cols = c(model_code, model_id),
      names_from = param, 
      values_from = value)
  
  return(.pivot_params)
}

pivot_metrics_tibble <- function(metrics, code){
  
  ## this should probably not be static, but I dont see it changing. 
  info_cols <- c("model_type", "id", "model_code", "model_id")
  
  # verify_is_tibble(metrics, "metrics")
  # verify_is_string(code, "code")
  # verify_code_in_tibble(code, params)
  
  .pivot_metrics <- metrics |> 
    filter(model_code == code) |> 
    pivot_longer(
      cols = -any_of(info_cols),
      names_to = "metric", 
      values_to = "score")

  return(.pivot_metrics)
  
}

parse_metric_column <- function(metrics){
  
  # verify_is_tibble(metrics, "metrics")
  
  .parse_metrics <- metrics |>
    mutate(
      average_type = str_extract(metric, "[a-z]+$"),
      metric = str_remove(metric, "beta_"),
      metric_type = str_extract(metric, "^[a-z]+[0-9]*"), 
      average_type = if_else(average_type == "accuracy", "NA", average_type)
      )
    
  return(.parse_metrics)
  
}

link_model_params <- function(metrics, params){
  
  # verify_is_tibble(metrics, "metrics")
  # verify_is_tibble(params, "params")
  
  .linked_tibble <- inner_join(metrics, params, 
                               by = c("model_id", "model_code"))

  return (.linked_tibble)
  
}

generate_model_tibble <- function(metrics, params, code){
  
  verify_is_tibble(metrics, "metrics")
  verify_is_tibble(params, "params")
  verify_is_string(code, "code")
  verify_code_in_tibble(params, code)
  
  # extract_hyperparams(params, code)
  
  .params <- pivot_param_tibble(params = params, code = code)
  
  .model <- pivot_metrics_tibble(metrics = metrics, code = code) |> 
    parse_metric_column() |> 
    link_model_params(params = .params)
  
  return(.model)
  
}
```


```{r}
extract_hyperparams(params, code = "KNN")
```

```{r}
generate_model_tibble(metrics = metrics, params = params, code = "KNN")
```


```{r}



## extract the hyperparams
hyperparams <- params |> 
    filter(model_code == "KNN") |> 
    pluck("param") |> 
    unique()

## filter than pivot the params table
knn_params <- params |> 
  filter(model_code == "KNN") |> 
  pivot_wider(id_cols = c(model_code, model_id), 
              names_from = param, 
              values_from = value)

## combine the metrics table - but filter the metrics table first. 
knn_df <- metrics |> 
  filter(model_code == "KNN") |> 
  pivot_longer(cols = -any_of(info_cols), 
               names_to = "metric", 
               values_to = "score") |> 
  mutate(
    average_type = str_extract(metric, "[a-z]+$"),
    metric = str_remove(metric, "beta_"),
    metric_type = str_extract(metric, "^[a-z]+[0-9]*"), 
    average_type = if_else(average_type == "accuracy", "NA", average_type)
         ) |> 
  inner_join(knn_params, by = c("model_id", "model_code"))

knn_df

```

```{r}

knn <- knn_df |> 
  summarise(.by = c(model_id, metric, metric_type, average_type), 
            mean_score = mean(score, na.rm = T), 
            sd_score = sd(score, na.rm = T)) |> 
  inner_join(knn_params, by = "model_id")

knn

```


```{r}

knn |> 
  ggplot(aes(x = as.numeric(n_neighbors), 
             y = mean_score, 
             colour = metric_type, 
             group = metric_type))+
  geom_point(alpha = .8, size = 1) +
  # scale_x_log10() +
  geom_smooth(se = F) +
  facet_grid(~weights)

```

```{r}

knn |> 
  ggplot(aes(x = as.numeric(n_neighbors), 
             y = mean_score, 
             colour = average_type, 
             group = average_type))+
  geom_point(alpha = .8, size = 1) +
  geom_smooth(se = F) +
  # scale_x_log10() +
  facet_grid(~weights)

```

